---
title: "CBE-LSE Bibliometric Analysis"
author: "Caleb Trujillo, Darcie Nelson, Rachel Kudlacz, Germaine Ng"
date: "4/1/2020"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require("devtools")
require("rgexf")
require("bibliometrix")
#devtools::install_github("massimoaria/bibliometrix")
library(bibliometrix)
library(tidyverse)
library(networkD3)
library(rgexf)
```

##Introduction

There has tremendous growth in the area undergraduate biology research over the last two decades. This study attempts to summarize and analyze the progress of this growth. 

### Summary of initial data set
This is a placeholder for the inital data set
Whole group
```{r dataset}
txt <- c("rawdata/VQD/20200315_QDV_WoS_Record1to500_QualResearch_KW.txt",
         "rawdata/VQD/20200315_QDV_WoS_Record501to1000_QualResearch_KW.txt",
         "rawdata/VQD/20200315_QDV_WoS_Record1001to1500_QualResearch_KW.txt",
         "rawdata/VQD/20200315_QDV_WoS_Record1501to2000_QualResearch_KW.txt"
         )
         
data <- convert2df(file = txt, dbsource = 'wos', format = "plaintext")
results <- biblioAnalysis(data, sep = ";")

summary(results)
```


Document Cocitation Analysis
```{r DCA, echo=FALSE, fig.width = 50, fig.asp = .618}
#INSERT FUNCTION FOR CREATING DOCUMENT COCITATION NETWORK using 'data' file
# Create a co-citation network
NetMatrix <- biblioNetwork(data, analysis = "co-citation", network = "references", sep = ";")

# Plot the network
net <- networkPlot(NetMatrix, n = dim(NetMatrix)[1], Title = "Co-Citation Network Qualitative Research with at least 8 co-citations", type = "auto", size.cex = TRUE, remove.multiple=TRUE, labelsize = 10, edgesize = 5, edges.min = 8, label.n = 30, cluster = "louvain", #halo = TRUE, weighted = TRUE, 
                  remove.isolates = TRUE, label.cex = TRUE)

#plot(net$graph, vertex.label.family = "Helvetica")
#names(net$nodeDegree["american association 2011-1"])<- "AAAS 2011"
net$nodeDegree
gnet<-igraph.to.gexf(net[["graph"]])
#g<-igraph_to_networkD3(net$graph)
#forceNetwork(Links = g$links, Nodes = g$nodes, Source = 'source',
             #Target = 'target', NodeID = 'name', fontSize = 10, 
             #Group = 1, zoom = TRUE, bounded = FALSE)
```
Text to explain what is shown in the figures.



